  version: '3.3'

  volumes:
    postgres_data:
    static:
    media:
  services:
    db:
      image: postgres:13.1
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env
      restart: always
    web:
      image: helenspring/yamdb:latest
      restart: always
      volumes:
        - .:/code
        - static:/code/static/
      depends_on:
        - db
      env_file:
        - ./.env
    nginx:
      image: nginx:1.19.5-alpine
      container_name: nginx
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./static:/var/html/static/
        - ./media:/var/html/media/
      ports:
        - "1337:80"
      env_file:
        - ./.env
      depends_on:
        - web
